### ISSUE TITLE
wayland issue with missing xsel

### ISSUE THREAD

**Issue by ninuzzo** [japanoise/sandy#1]
I am running sandy 0.4 in Wayland and since xsel is missing I keep getting warnings like:

sh: 1: xsel: not found

You should support Wayland and use wl-copy and wl-paste of the wl-clipboard package

**Comment by japanoise** [comment]
Hi, I'm not actively maintaining this and I don't use wayland, so I won't be able to do this myself, but the xsel lines are in config.def.h: https://github.com/japanoise/sandy/blob/50204e1ff24489f074d42df5cebb32f9f160ecf1/config.def.h#L48

You should be able to change those in your local config.h, or submit a PR to update config.def.h that can support both X and wayland
